# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               esWizardry
tagline:             'embedded system, coding and everything I passionate.'
description:         'More on embedded system, coding Technology, my thought and everything I passionate.'
url:                 https://eswizardry.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              eswizardry
  url:               https://eswizardry.github.io/
  email:             edrit011@gmail.com

# Custom vars
version:             1.0.0
